version: '3.1'

services:
  mysql-db:
    image: mysql:8.2.0
    environment:
      # rootユーザーのpassword設定
      MYSQL_ROOT_PASSWORD: rootpass
      TZ: 'Asia/Tokyo'
    ports:
      # ホスト側のポート:コンテナ側のポート
      - 3306:3306
    volumes:
      # DBの初期設定を行うファイルをコピーする
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin:5.2
    depends_on:
      - mysql-db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS='mysql-db'
    ports:
      - "3000:80"
    volumes:
      - ./phpmyadmin/sessions:/sessions
  
  manager:
    image: python:3.10.12
    volumes:
      - ./manager/requirements.txt:/requirements.txt
      - ./manager/manager.py:/manager.py
    command: >
      bash -c "pip install -r requirements.txt
      && python manager.py"
    ports:
      - "8001:5000"

  stcak_server:
    image: python:3.10.12
    volumes:
      - ./stack_server/requirements.txt:/requirements.txt
      - ./stack_server/stack_server.py:/stack_server.py
    command: >
      bash -c "pip install -r requirements.txt
      && python stack_server.py"
    ports:
      - "8000:5000"